anga_gest_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('angajati.urls')),
]

              # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

angajati/urls.py
from django.urls import path

from angajati import views

urlpatterns = [
    path('', views.home_page_view, name='home'),

    path('creaza_angajat/', views.create_angajat_view, name='creaza_angajat'),
    path('upload_angajati/', views.upload_angajati_view, name='upload_angajati'),
    path('employee_details/<int:angajat_id>/', views.employee_details_view, name='details_employee'),
    path('employees_actives/', views.employees_actives_view, name='employees_actives'),
    path('employee_all_view/', views.employee_all_view, name='employee_all_view'),
    path('update_angajat/<int:pk>/', views.EmployeeUpdateView.as_view(), name='update_angajat'),
    path('delete_angajat/<int:pk>/', views.disable_employee_view, name='delete_angajat'),
    path('export_csv_angajati', views.export_csv_angajati, name='export_csv_angajati'),
    path('download_file_for_upload_angajati/', views.download_file_for_upload_angajati,
         name='download_file_for_upload_angajati'),

    path('upload_csv/', views.upload_pontaj_csv_view, name='upload_csv'),
    path('pontaj_lunar/', views.pontaj_lunar_view, name='pontaj_lunar'),
    path('pontaj_simplificat/', views.pontaj_simplificat_view, name='pontaj_simplificat'),
    path('pontaj_lunar_angajat/<int:angajat_id>/', views.pontaj_lunar_angajat_view, name='pontaj_lunar_angajat'),
    path('status_angajat_update/<int:pk>/', views.StatusAngajatUpdateView.as_view(), name='status_angajat_update'),
    path('absente_angajat/<int:angajat_id>', views.absente_angajat_view, name='absente_angajat'),


    path('create_contract_angajat/<int:employee_id>/', views.create_contract_angajat_view,
         name='create_contract_angajat'),
    path('contracts_all/<int:angajat_id>/', views.contracts_all_view, name='contracts_all'),
    path('contracts_all_employees/', views.contracts_all_employees_view, name='contracts_all_employees'),
    path('update_contract/<int:pk>/', views.ContractUpdateView.as_view(), name='update_contract'),


    path('create_status/', views.create_status_view, name='create_status'),
    path('status_all/', views.status_all_view, name='status_all'),
    path('status_detail/<int:pk>/', views.StatusDetailView.as_view(), name='status_detail'),
    path('update_status/<int:pk>/', views.StatusUpdateView.as_view(), name='update_status'),
    path('delete_status/<int:pk>/', views.StatusDeleteView.as_view(), name='delete_status'),

    path('create_functie/', views.create_functie_view, name='create_functie'),
    path('functie_all/', views.functie_all_view, name='functie_all'),
    path('functie_detail/<int:pk>/', views.FunctieDetailView.as_view(), name='functie_detail'),
    path('update_functie/<int:pk>/', views.FunctieUpdateView.as_view(), name='update_functie'),
    path('delete_functie/<int:pk>/', views.FunctieDeleteView.as_view(), name='delete_functie'),

    path('create_companie/', views.create_companie_view, name='create_companie'),
    path('companie_detail/<int:pk>/', views.CompanieDetailView.as_view(), name='companie_detail'),
    path('update_companie/<int:pk>/', views.CompanieUpdateView.as_view(), name='update_companie'),
    path('delete_companie/<int:pk>/', views.CompanieDeleteView.as_view(), name='delete_companie'),

    path('create_comment/<int:employee_id>/', views.create_comment_view, name='create_comment'),
    path('comments_angajat/<int:angajat_id>/', views.comments_angajat_view, name='comments_angajat'),
    path('comment_update/<int:pk>/', views.CommentUpdateView.as_view(), name='comment_update'),

    path('alte_gestiuni/', views.alte_gestiuni, name='alte_gestiuni'),

    # path('select_status_period/<int:angajat_id>', views.select_status_period_view, name='select_status_period'),

]

# path('creare_angajat/', views.angajat_create_and_register_view, name='create_register'),
# path('create_contract_details/<int:employee_id>/', views.angajat_contract_and_status_create_view, name='create_contract_details'),
# path('update_contract_status/<int:employee_id>/', views.status_and_contract_update_view, name='update_contract_status'),
# path('update_contract/<int:employee_id>/', views.contract_update_view, name='update_contract'),
# path('update_status/<int:status_id>/', views.status_update_view, name='update_status'),
# path('calendar/', views.CalendarView.as_view(), name='calendar'),
# path('pontaj_all/', views.pontaj_all_view, name='pontaj_all'),
# path('pontaj_list/', views.pontaj_list, name='pontaj_list'),
# path('calendar/', views.CalendarView.as_view(), name='calendar'),

# path('staff_view/', views.staff_homepage_view, name='staff_view'),
# path('hello/', views.hello, name='hello'),
# path('home', views.hello, name='home'), probat si asa dar cand dam run si apoi click pe link jos, in run
# apoi pe pagina ce se deschide adaugam in url "/home" - primul parametru din path
# path('', views.HomePageView.as_view(), name='home'),
# path('user_detail/', views.UsersPageView.as_view(), name='detail_user'),
# path('delete_angajat/<int:pk>/', views.EmployeeDeleteView.as_view(), name='delete_angajat'),
# path('employee_details/<int:pk>/', views.EmployeeDetailsView.as_view(), name='details employee'),
# primul parametru din path e ceea ce scriem in link daca vrem sa intram
# pe un anume angajat direct din link(ex:in link avem doar http://127.0.0.1:8001/
# adaugam "/detalii_angajat/<id-ul angajatului dorit>"
# (sau ce ne apare daca dam click pe un angajat)
## al 2-lea parametru este referinta la view-ul dorit, daca e o clasa se trece si ".as_view()",
## daca e functie doar views."nume_functie"
### al 3-lea parametru e NUMELE UNIC pe care trebuie sa il atribuim si care
### apoi il putem folosi in template ca si url, ex:
### href="{%  url 'angajat_detalii' angajat.id %}" - vezi template 'homepage.html'

angajati/models.py
import datetime
from datetime import date, timedelta, datetime
#!!! fara importul de mai sus imi da eroare la pontaj lunar, cu date time... am lasat asa, chiar daca e "nefolosit"
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _


from django.contrib.auth.models import AbstractUser, PermissionsMixin, User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models
from django.utils import timezone
from django_iban.fields import IBANField
from angajati.validators import validare_cnp


class ModelMixin:
    data_introducere = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{str(self.data_introducere)}"


class Employee(ModelMixin, models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cnp = models.CharField(max_length=13, validators=[MinLengthValidator(13), validare_cnp, MaxLengthValidator(13)],
                           null=True, blank=True)
    nume_angajat = models.CharField(max_length=60)
    prenume_angajat = models.CharField(max_length=60)
    id_pontaj = models.BigIntegerField(unique=True, null=True, blank=True)
    telefon = models.CharField(max_length=18, default="0", null=True, blank=True)
    email = models.EmailField(default="ceva@ceva.com", null=True, blank=True)
    data_nasterii = models.DateField(default=timezone.now, null=True, blank=True)
    religie = models.CharField(max_length=30, default="religie nedefinita", null=True, blank=True)
    data_angajare = models.DateField(default=timezone.now, null=True, blank=True)
    data_introducere = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.nume_angajat.capitalize()} {self.prenume_angajat.capitalize()} ' \
               f'Id pontaj:{self.id_pontaj}'

    def save(self, *args, **kwargs):
        try:
            status_set = Status.objects.get(abbreviated_value='ANG')
            super(Employee, self).save(*args, **kwargs)
            StatusAngajat.objects.create(angajat_id=self.id, status=status_set)

        except ObjectDoesNotExist:
            Status.objects.create(view_value="ANGAJAT", abbreviated_value='ANG')
            status_set = Status.objects.get(abbreviated_value='ANG')
            super(Employee, self).save(*args, **kwargs)
            StatusAngajat.objects.create(angajat=self, status=status_set)

# TODO pop up non-blocant daca are sub 18 ani!

class Comment(ModelMixin, models.Model):
    angajat = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    continut = models.TextField()
    data_introducere = models.DateTimeField(auto_now=True, )
    nume_autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    # in settings am modificat TIME_ZONE = 'Europe/Bucharest'

    def __str__(self):
        return f"{self.continut[:15]} \n |posted by:{self.nume_autor} on " \
               f"{self.data_introducere.strftime('%Y-%m-%d ora: %H:%M')}"


class Status(ModelMixin, models.Model):
    view_value = models.CharField(max_length=100)
    abbreviated_value = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.abbreviated_value}:{self.view_value}"


# TODO vreau sa pot selecta un interval de mai multe zile, de exemplu pentru Boala/ Concediu
class StatusAngajat(ModelMixin, models.Model):
    angajat = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True, blank=True)
    date_time_in = models.DateTimeField(default=timezone.now, null=True, blank=True)
    date_time_out = models.DateTimeField(default=timezone.now, null=True, blank=True)
    note = models.TextField(default=None, null=True, blank=True)

    def hours_worked(self):
        ore_lucrate = self.date_time_out - self.date_time_in
        if str(ore_lucrate) == "0:00:00":
            ore_lucrate = 0
        return ore_lucrate

    def __str__(self):
        return f"{self.angajat}:{self.status}//in:{self.date_time_in}//out:{self.date_time_out}"


    # https://django-durationfield.readthedocs.io/en/latest/
    # de implementat logica pentru diferite status-uri
    # ore_lucrate = datetime.combine(date.min, self.last_out) - datetime.combine(date.min, self.first_in)


class Functie(ModelMixin, models.Model):
    view_value = models.CharField(max_length=100)

    def __str__(self):
        return self.view_value


class ContractDetail(ModelMixin, models.Model):
    angajat = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True)
    functie = models.ForeignKey(Functie, on_delete=models.CASCADE)
    salar_brut = models.DecimalField(max_digits=10, decimal_places=2)
    naveta = models.CharField(max_length=50, default="URBAN",
                              choices=[("URBAN", "URBAN"), ("RURAL", "RURAL"), ("ALTA SITUATIE", "ALTA SITUATIE")])
    data_inceperii = models.DateField(default=timezone.now)
    data_incetarii = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.functie}, {self.salar_brut} brut, data:{self.data_inceperii};{self.naveta}"

# TODO implementeaza si pentru django admin limitare la 1 singura companie
class Company(models.Model):
    nume = models.CharField(max_length=250)
    cui = models.CharField(max_length=15, default="RO........", null=True, blank=True)
    cif = models.CharField(max_length=15, default="J./.../....", null=True, blank=True)
    adresa = models.TextField(null=True, blank=True)
    email = models.EmailField(default="undefined@undefined.com", null=True, blank=True)
    website = models.URLField('Website', max_length=200, null=True, blank=True)
    telefon = models.CharField(max_length=100)
    cont_bancar_ron = IBANField(enforce_database_constraint=True, unique=True, null=True, blank=True)
    cont_bancar_eur = IBANField(enforce_database_constraint=True, unique=True, null=True, blank=True)
    data_infiintarii = models.DateField(null=True, blank=True)
    cod_caen = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return f"{self.nume}"

# functie = models.CharField(max_length=80, default="OPERATOR",
#    choices=[("OPERATOR", "OPERATOR"), ("OPERATOR CNC", "OPERATOR CNC"),
#          ("VOPSITOR", "VOPSITOR"), ("TEHNICIAN CALITATE", "TEHNICIAN CALITATE"),
#          ("LACATUS MECANIC", "LACATUS MECANIC"), ("MAGAZINER", "MAGAZINER"),
#          ("SUDOR", "SUDOR")],
#                            null=True, blank=True)

# class Pontaj(models.Model):
#     date = models.DateField(null=True, blank=True)
#     free_day = models.BooleanField(default=False)
#     weekend = models.BooleanField(default=False)

# _in = models.DateTimeField(null=True, blank=True)
# _out = models.DateTimeField(null=True, blank=True)

# class OreLucrate(models.Model):
#     nume = models.CharField(max_length=250)
#     prenume = models.CharField(max_length=250)
#     nr_cartela = models.CharField(max_length=10)
#     ziua = models.DateTimeField(default=timezone.now, null=True, blank=True)
#     zile_lucratoare =
#     ore_lucratoare =
#     status_zi = models.CharField(max_length=100)
#
#     data_introducere = models.DateTimeField(auto_now=True)


# class User(PermissionsMixin, AbstractUser):
#     parent_angajat = models.ForeignKey(Employee, on_delete=models.CASCADE)
# voi folosi model-ul user din django
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
# https://stackoverflow.com/questions/67560240/how-to-link-an-existing-model-with-user-model-in-django
# class User(models.Model):
#     nume_user = models.CharField(max_length=15)
#     data_creare = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.nume_user


# TODO user profiles
# class UserProfile(models.Model):
#     TYPE_CHOICES = (
#         ('administrative', 'administrative'),
#         ('birouri', 'birouri'),
#         ('employee', 'employee')
#         )

templates/nefolosite/angjat_create.html
{% extends 'base.html' %}

{% block title %}Angajat Create{% endblock %}

templates/nefolosite/calendar.html
{% extends 'base.html' %}
{% block title %}Calendar{{ object.angajat.nume_angajat }}{% endblock %}
{% block content %}
    {{ calendar }}

{% endblock %}

templates/nefolosite/create_and_register_angajat.html
{% extends 'base.html' %}
{% block title %}Creaza Angajat{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ angajat_form.as_p }}
        {{ user_form.as_p }}
    <button type="submit" value="create" name="_create" style="background-color: #0dcaf0">Creeaza Angajat</button>
    <button type="submit" value="else" name="_else" style="background-color: #ffca2c">Creeaza si adauga altul</button>
    <button type="submit" value="continue" name="_continue" style="background-color: #67bb6a">Creeaza si detalii contractuale</button>
    </form>
{% endblock %}

templates/nefolosite/create_contract_and_status_angajat.html
{% extends 'base.html' %}
{% block title %}Contract&Status Angajat{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ contract_form.as_p }}
        {{ status_form.as_p }}
    <button type="submit" style="background-color: #0dcaf0">Adauga date angajat</button>
    </form>
{% endblock %}

templates/nefolosite/employee_details.html
{#!!! INLOCUITA CU employee_detail.html#}

{% extends 'base.html' %}

{% block title %} {{ angajat.nume_angajat.capitalize }} {{ angajat.prenume_angajat.capitalize }} {% endblock %}
{% block content %}

    <div class="row flex justify-content-start ms-1" style="width: 99%">
        <div class="col-9 m-1 border border-primary border-5 rounded">
            <h1>Angajat:</h1>
            <h2>{{ angajat }}</h2>
            <h1>Statusuri:</h1>
            {% for status in statuses reversed %}
                {#                <h2>{{ status.status.view_value }}, data: {{ status.date_time_in.date }} iesire: {{ status.date_time_out }},#}
                {#                    intrare time: {{ status.date_time_in.time }}</h2>#}
                <h4> {{ status.status.abbreviated_value }} - {{ status.date_time_in.astimezone.date }}|||
                    {#                    {{ status.status.abbreviated_value }}, in: {{ status.date_time_in.astimezone.date }},#}
                    {#                    {{ status.date_time_in.astimezone.hour }}:{{ status.date_time_in.astimezone.minute }},#}
                    in --> {{ status.date_time_in.astimezone.hour }}:{{ status.date_time_in.astimezone.minute }},
                    out --> {{ status.date_time_out.astimezone.hour }}:{{ status.date_time_out.astimezone.minute }},
                    total ore: {{ status.hours_worked }}
                    {#                    {{ status.date_time_out.astimezone.date }}#}
                    <a class="btn btn-primary m-5 btn-sm"
                       style="color: black"
                       href="{% url 'status_angajat_update' status.id %}"
                       role="button">Update status</a></h4>
                {#                <a class="btn btn-primary m-5 btn-sm" style="color: black" href="{% url 'status_angajat_update' status.id %}"#}
                {#                       role="button">Update status</a>#}
                {#                <h2>{{ status.status.view_value }}, {{ status.date }} iesire: {{ status.last_out }},#}
                {#                    intrare: {{ status.first_in }}</h2>#}
            {% endfor %}

            {% for detaliu in detalii %}
                <h1><b>Contract</b></h1>
                <h3><b>{{ detaliu }}</b> <a class="btn btn-primary m-5" style="color: black"
                                            href="{% url 'update_contract' detaliu.id %}"
                                            role="button">Update contract</a></h3>
                <h3>start: {{ detaliu.data_inceperii }}</h3>
                <h3>end: {{ detaliu.data_incetarii }}</h3>
                <h3>introdus in: {{ detaliu.angajat.data_introducere }}</h3>
                <h3>{{ detaliu.angajat.cnp }}</h3>

                {#                aici pun butonul de update pt contract detaliu.id#}
            {% endfor %}
            <h2><b>Commentarii</b></h2>
            {% for comentariu in comentarii reversed %}
                <p>{{ comentariu }}</p>
            {% endfor %}
            <h2>Statusuri</h2>
        </div>
        {#        {% if statuses|last != 'LICHIDAT' %}#}

        {#        {% endif %}#}
        {#        {% with status=statuses|last %}#}
        {#            {% if status != 'LICHIDAT' %}#}
        {% if last_status.status.view_value != 'LICHIDAT' %}
            <div class="col-2  m-auto">
                {#                <div class="col m-auto border border-warning border-5 rounded">#}
                {#                <a class="btn btn-success mt-1" style="color: black; background-color: #0dbf92"#}
                {#                    href="{% url 'create_contract_details' %}" role="button">Modifica detalii contract</a>#}
                {#                </div>#}
                <div class="col m-auto border border-warning border-5 rounded">
                    <a class="btn btn-warning m-5" style="color: black" href="{% url 'update_angajat' angajat.id %}"
                       role="button">Update Angajat</a>
                </div>
                <br>
                <div class="col m-auto border border-primary border-5 rounded">
                    <a class="btn btn-primary m-5" style="color: black"
                       href="{% url 'create_contract_angajat' angajat.id %}"
                       role="button">Create new contract</a>
                </div>
                <br>
                <div class="col m-auto border border-danger border-5 rounded">
                    {#                {% for status in statuses %}#}
                    <a class="btn btn-danger m-5" style="color: black"
                       href="{% url 'delete_angajat' angajat.id %}" role="button">Delete Angajat</a>
                </div>
            </div>
        {% else %}
            <div class="col-2  m-auto">

                <div class="col m-auto border border-primary border-5 rounded">
                    <a class="btn btn-primary m-5" style="color: black"
                       href="{% url 'create_contract_angajat' angajat.id %}"
                       role="button">Create new contract</a>
                </div>
                <br>
                <div class="col m-auto border border-primary border-5 rounded">
                    <a class="btn btn-primary m-5" style="color: black" href="{% url 'update_status' angajat.id %}"
                       role="button">Update status</a>
                </div>
                <br>
                <div class="col m-auto border border-danger border-5 rounded">
                    {#                {% for status in statuses %}#}
                    <a class="btn disabled btn-light m-5" style="color: black"
                       role="button">Angajat dezactivat</a>

                </div>
            </div>
        {% endif %}
        {#        {% endwith %}#}
    </div>
    <div class="row flex justify-content-start m-1">
        <p>{% include 'registration/login_out_buttons.html' %}</p>
    </div>
{% endblock %}

{#        {% endwith %}#}

{#            <div class="col m-auto border border-warning border-5 rounded">#}
{#                <a class="btn btn-warning m-5" style="color: black" href="{% url 'update_angajat' angajat.id %}" role="button">Update Angajat</a>#}
{#            </div><br>#}
{#            <div class="col m-auto border border-danger border-5 rounded">#}
{#                {% for status in statuses %}#}
{#                {% with status=statuses|first %}#}
{#                    {% if status.status.view_value != 'LICHIDAT' %}#}
{##}
{#                        <a class="btn btn-danger m-5" style="color: black"#}
{#                                               href="{% url 'delete_angajat' angajat.id %}" role="button">Delete Angajat</a>#}
{#                    {% else %}#}
{#                        <a class="btn disabled btn-light m-5" style="color: black"#}
{#                                role="button">Angajat dezactivat</a>#}
{##}
{#                    {% endif %}#}
{#                {% endwith %}#}
{#                {% endfor %}#}
{#            </div>#}


{#            <div class="col m-auto border border-danger border-5 rounded">#}
{#                <a class="btn btn-danger m-5" style="color: black" href="{% url 'delete_angajat' angajat.id %}" role="button">Delete Angajat</a>#}
{#            </div>#}
{#             <a class="btn btn-danger m-5" style="color: black" href="{% url 'delete_angajat' angajat.id %}" role="button">Delete Angajat</a>#}
{#        </div>#}
{#        <div class="col-2  m-auto border border-danger border-5 rounded">#}
{#            <a class="btn btn-warning m-5" style="color: black" href="{% url 'update_angajat' angajat.id %}" role="button">Update Angajat</a>#}
{#        </div>#}
{#        <p style="margin-top: 5px">{% include 'registration/login_out_buttons.html' %}</p>#}
{#    </div>#}
{##}
{#    <h2>{{ details_employee.nume_angajat }}-{{ details_employee.prenume_angajat }}</h2>#}
{#    <p> Functie: <b>{{ details_employee.functie.upper }}</b>;#}
{#        Data angajarii:<b>{{ details_employee.data_angajarii }}</b></p>#}
{#    <p><b>StatusAngajat:</b> {{ details_employee.get_status_display }} </p>#}
{#    <p><b>StatusAngajat:</b> {{ details_employee.status }} </p>#}
{#    <p> Data introducere:<b>{{ details_employee.data_introducere.date }}</b></p>#}
{#    {% for comentariu in comentarii %}#}
{#        <h5>Comentarii/ Note</h5>#}
{#        <p> {{ comentariu.continut }}</p>#}
{#    {% endfor %}#}
{##}
{#    <p style="margin-top: 5px">{% include 'registration/login_out_buttons.html' %}</p>#}
{##}
{#{% endblock %}#}

templates/nefolosite/pontaj_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Pontaj All{% endblock %}

{% block content %}
    <a href="{% url 'export_csv_angajati' %}">Export</a>

    <div class="container-flex ms-3" style="overflow-y: auto;overflow-x: auto;max-width: fit-content">
        <h2><b>Pontaj Angajati</b></h2>
        <table id="myTable" class="border-3" style="border-color: grey">
            <thead>
            <tr>
                <th class="bg-dark"><input id="" type="checkbox" onclick="toggleSelect()"/></th>
                {% for head in table_head %}
                    <th class="bg-dark text-secondary" style="text-align: center">
                        <div>
                            <p>{{ head }}</p>
                        </div>
                        <div class="d-flex">
                            <span>
                                <input name="{{ head }}" style="width: 140px" class="form-fluid m-2 bg-white"
                                       type="text"
                                       id="{{ head }}"
                                       onkeyup="myFunction({{ forloop.counter }},id)"
                                       placeholder="Search...">
                            </span>
{#                            <span>#}
{#                                <button type="button" class="btn btn-outline-secondary "#}
{#                                        onclick=sortTable({{ forloop.counter }})><i#}
{#                                        class="bi bi-sort-alpha-down"></i>#}
{#                                </button>#}
{#                            </span>#}
                        </div>
                    </th>
                {% empty %}
                            <p>There is no data yet!</p>>
                {% endfor %}
                <th class="bg-dark"></th>
                <th class="bg-dark"></th>
                <th class="bg-dark"></th>
            </tr>
            </thead>
            <tbody>
                {% if request.user.is_staff %}
                    {% for angajat_statuses in all_statusuri %}
                        {% for status in angajat_statuses %}
                            <tr>
                                <td class="bg-dark"><input value="{{ column_value.id }}" type="checkbox" name="chk"/></td>
                                <td class="bg-dark disabled text-secondary" style="text-align: center">
                                    <a href="{% url 'details_employee' status.angajat.id %}">
                                    {{ status.angajat.nume_angajat }}</a>
                                </td>
                                <td class="bg-dark disabled text-secondary" style="text-align: center">
                                    <a href="{% url 'details_employee' status.angajat.id %}">
                                    {{ status.angajat.prenume_angajat }}</a>
                                </td>
                                <td class="bg-dark disabled text-secondary"
                                    style="text-align: center">
                                    {{ status.date_time_in.astimezone.date.day}}/{{ status.date_time_in.astimezone.date.month}}  --
                                    {{ status.date_time_in.astimezone.hour }}:{{ status.date_time_in.astimezone.minute }}   ---</td>
                                <td class="bg-dark disabled text-secondary"
                                    style="text-align: center">
                                    ---   {{ status.date_time_out.astimezone.hour }}:{{ status.date_time_out.astimezone.minute }}
                                    -- {{ status.date_time_out.astimezone.date.day}}/{{ status.date_time_out.astimezone.date.month}}
                                </td>
                                <td class="bg-dark disabled text-secondary"
                                    style="text-align: center">{{ status.hours_worked }}</td>
                                <td class="bg-dark"><a class="btn btn-primary m-2 btn-sm" style="color: black"
                                                       href="{% url 'status_angajat_update' status.id %}"
                                                       role="button">Update status</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endfor %}


                {% endif %}
            </tbody>


        </table>
    </div>

{% endblock %}



{#/////#}
{#template cu pontaj, fara tabel#}
{#    {% if request.user.is_staff %}#}
{#        <div class="container-flex ms-3">#}
{#            {% for angajat_statuses in all_statusuri %}#}
{#                {% for status in angajat_statuses %}#}
{#                    <div>#}
{#                        {{ status.angajat.nume_angajat }}#}
{#                        {{ status.angajat.prenume_angajat }}#}
{#                        in: {{ status.date_time_in }}#}
{#                        out: {{ status.date_time_out }}#}
{#                        hours: {{ status.hours_worked }}#}
                        {#                        <span><a class="btn btn-primary m-2" style="color: black"#}
                        {#                                 href="{% url 'update_status' status.id %}"#}
                        {#                                 role="button">Update status</a></span>#}
{#                        <span><a class="btn btn-primary m-2 btn-sm" style="color: black"#}
{#                                 href="{% url 'status_angajat_update' status.id %}"#}
{#                                 role="button">Update status</a></span>#}
{#                    </div>#}
{#                {% endfor %}#}
{#            {% endfor %}#}
{#        </div>#}
{#    {% endif %}#}
{# ///// #}